name: VaultPayday
version: '${version}'
main: me.devupdates.vaultPayday.VaultPayday
api-version: '1.20'
description: 'SA:MP-inspired payday system for Minecraft servers with JobsReborn integration'
author: devupdates
website: 'https://github.com/devupdates/VaultPayday'

# Required dependencies
depend: [Vault, Jobs]

# Optional soft dependencies
softdepend: [PlaceholderAPI]

# Plugin load order
load: POSTWORLD

# Commands
commands:
  payday:
    description: 'Show your current payday progress and pending balance'
    usage: '/payday'
    permission: vaultpayday.check
    permission-message: '§cYou do not have permission to use this command!'
  
  vaultpayday:
    description: 'Main VaultPayday admin command'
    usage: '/vaultpayday <reload|reset|settime|info|stats>'
    permission: vaultpayday.admin
    permission-message: '§cYou do not have permission to use this command!'
    aliases: [vp, vpd]

# Permissions
permissions:
  vaultpayday.*:
    description: 'Gives access to all VaultPayday permissions'
    children:
      vaultpayday.check: true
      vaultpayday.admin: true
      vaultpayday.multiplier.*: true
    default: op
  
  vaultpayday.check:
    description: 'Allows player to check their payday progress'
    default: true
  
  vaultpayday.admin:
    description: 'Allows access to admin commands'
    default: op
  
  vaultpayday.multiplier.vip:
    description: 'VIP payday multiplier (1.5x)'
    default: false
  
  vaultpayday.multiplier.premium:
    description: 'Premium payday multiplier (2.0x)'
    default: false
  
  vaultpayday.bypass:
    description: 'Bypass payday system and receive instant payments'
    default: false
